import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import "../styles/scss/bootstrap.scss";
// import "@/styles/custom.scss";
import { NextIntlClientProvider } from "next-intl";
import { Provider } from "react-redux";
import store from "@/store/store";
import { Providers } from "@/app/utils/providers";
import { ThemeProvider } from "next-themes";
import LoadingProvider from "@/components/layout/LoadingBar";
import "sweetalert2/src/sweetalert2.scss";
import "react-loading-skeleton/dist/skeleton.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Webloka",
  description: "Generated by Webloka",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/npm/@phosphor-icons/web@2.1.2/src/regular/style.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/npm/@phosphor-icons/web@2.1.2/src/bold/style.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/npm/@phosphor-icons/web@2.1.2/src/duotone/style.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/npm/@phosphor-icons/web@2.1.2/src/fill/style.css"
        />
        <script src="https://cdn.jsdelivr.net/npm/@phosphor-icons/web@2.1.2"></script>
      </head>
      <body>
        <ThemeProvider attribute="data-bs-theme" defaultTheme="light" enableSystem={false}>
          <Providers>
            <NextIntlClientProvider>
              <LoadingProvider>{children}</LoadingProvider>
            </NextIntlClientProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
